spring:
  profiles:
    active: dev,common #这样就引入其他模块的yml文件了，可以使用@value等方式取值。
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
erver:
  tomcat:
    uri-encoding: UTF-8
