spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/mall_tiny2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: mall
    password: 123456
  redis:
    host: 192.168.1.7 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tulingxueyuan: debug

aliyun:
  oss:
    endpoint: oss-cn-zhangjiakou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FnNvw5E5Do1SDtLNiyF # 访问身份验证中用到用户标识
    accessKeySecret: TjAUwSiod2caNFO8edetPgQNkLfu2N # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: hsy-tuling-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: tulingmall/images/ # 上传文件夹路径前缀

mybatis-plus:
  #??xml
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    #??sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl