version: '3'
services:
  zk:
    image: zookeeper
    container_name: zk
    ports:
      - 2181:2181
  dubbo-admin:
    image: chenchuxin/dubbo-admin
    container_name: dubbo-admin
    # 等待zk启动后再启动
    depends_on:
      - zk
    ports:
      - 8080:8080
    environment:
      - dubbo.registry.address=zookeeper://zk:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest