server:
  port: 8888

spring:
  application:
    name: mall-admin
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

redis:
  database: mall
  expire:
    common: 86400 # 24小时


