TOKEN_KEY: token
app:
  name: ????
  version: 1.0
dubbo:
  application:
    name: sso-web
  registry:
    address: zookeeper://192.168.10.33:2181
    protocol: zookeeper
server:
  port: 8031
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
