app:
  name: 登录页面
  version: 1.0
#tomcat conf
server:
  port: 8031
#dubbo conf
dubbo:
  application:
    name: e3-sso-web
  registry:
    address: zookeeper://192.168.10.33:2181
logging:
  level:
    root: info
    com.mall.sso: debug
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
#因为maven子工程会继承其他工程数据配置，需要屏蔽
#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

