app:
  name: 登录页面
  version: 1.0
#tomcat conf
server:
  port: 8033
spring:
  main:
    allow-circular-references: true
#dubbo conf
dubbo:
  application:
    name: mall-sso-web
  registry:
    address: zookeeper://192.168.10.251:2181
logging:
  level:
    root: info
    com.mall.sso: debug
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /error

jwt:
  secret: tuling-mall-admin  #服务端私钥（一定不能泄露）
  expiration: 86400   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字
#因为maven子工程会继承其他工程数据配置，需要屏蔽
#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
