server:
  port: 8030
app:
  name: 搜索页面
  version: 1.0
spring:
  application:
    name: seach-controller
# ====================== ↓↓↓↓↓↓ 配置dubbo↓↓↓↓↓↓ ======================
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.10.251:2181
    protocol: zookeeper


