SEARCH_RESULT_ROWS: 60
app:
  name: 搜索页面
  version: 1.0
dubbo:
  application:
    name: search-web
  registry:
    address: zookeeper://192.168.10.33:2181
    protocol: zookeeper
server:
  port: 8029
  servlet:
    context-path: /
    path: '*.html'
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

