app:
  name: 购物车
  version: 1.0
druid:
  allow:
    ip: 127.0.0.1
  login:
    user_name: root
    password: root
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e3mall?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-idle: 5
    max-wait-millis: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    port: 6379
dubbo:
  application:
    name: e3-cart
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://39.104.87.118:2181
    protocol: zookeeper
  scan:
    base-packages: com.e3mall.cart.service
server:
    port: 8020
#头部值
REDIS_ITEM_PRE2: ITEM_INFO
ITEM_CACHE_EXPIRE: 600000
#mq
rocketmq:
  producer:
    groupName: e3-manager
    namesrvAddr: 127.0.0.1:9876
    default: true
REDIS_CART_PRE: CART
