server:
  port: 8020
# dubbo config
#dubbo:
#  application:
#    name: mall-cart
#    qosPort: 22221
#  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
#  # 注册中心id
#  registry:
#    id: zookeeper-registry
#    # 注册中心协议
#    protocol: zookeeper
#    # 注册中心地址
#    address: 192.168.10.33:2181
#  # dubbo协议在20880端口暴露服务
#  # 协议名称
#  protocol:
#    name: dubbo
#    # 协议端口
#    port: 20886
#    # 协议访问log
#    accesslog: dubbo-access.log
#  # 重试次数
#  provider:
#    retries: 0
#    # 超时时间
#    timeout: 3000
#  # 注册监控中心
#  monitor:
#    protocol: registry
dubbo:
  application:
    name: mall-cart
    qosPort: 22221
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 192.168.10.33:2181

  # dubbo协议在20880端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20886
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000
  # 注册监控中心
  monitor:
    protocol: registry
spring:
  redis:
    host: 192.168.10.33
    port: 6379

#头部值
REDIS_CART_PRE: CART
