server:
  port: 8026
spring:
  application:
    name: order
  profiles:
    active: dynamic
  main:
    allow-bean-definition-overriding: true
    # ====================== ↓↓↓↓↓↓ 配置druid↓↓↓↓↓↓ ======================
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
      web-stat-filter:
        enabled: true
  redis:
    host: 192.168.10.251
    port: 6379
# ====================== ↓↓↓↓↓↓ dubbo配置 ↓↓↓↓↓↓ ======================
dubbo:
  application:
    name: mall-order
    qosPort: 22221
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 192.168.10.251:2181

  # dubbo协议在20880端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20882
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000
  # 注册监控中心
  monitor:
    protocol: registry

# MyBatis
mybatis:
  mapper-locations:
    - classpath:mybatis/*.xml
#    - classpath*:com/**/mapper/*.xml
#mq
rocketmq:
  producer:
    groupName: order-service
    namesrvAddr: 192.168.10.251:9876
    default: true
logging:
  level:
    root: info
    com.mall.order: debug
logstash:
  host: localhost
  enableInnerLog: false
pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true