druid:
  allow:
    ip: 127.0.0.1
  login:
    user_name: root
    password: root

dubbo:
  application:
    name: mall-search
    qosPort: 22221
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 192.168.10.33:2181

  # dubbo协议在20880端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20884
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000
  # 注册监控中心
  monitor:
    protocol: registry
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.10.33:3306/mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
es:
  host: 192.168.10.33
  port: 9200
  scheme: http
server:
  port: 8028
rocketmq:
  producer:
    groupName: mall-search
    namesrvAddr: 192.168.10.33:9876
    default: true
# MyBatis
mybatis:
  type-aliases-package: com.mall.pojo
  mapper-locations: classpath:/mybatis/*.xml
