rocketmq:
  producer:
    default: true
    groupName: e3-search
    namesrvAddr: 192.168.10.33:9876
server:
  port: 8023
  servlet:
    context-path: /
    path: '*.html'
  tomcat:
    uri-encoding: UTF-8

dubbo:
  application:
    name: item-web
  registry:
    address: zookeeper://192.168.10.33:2181
    protocol: zookeepe

