CONTENT_LUNBO_ID: 89
app:
  name: 首页
  version: 1.0
dubbo:
  application:
    name: portal-web
  registry:
    address: zookeeper://192.168.10.33:2181
    protocol: zookeeper
server:
  port: 8032
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp