app:
  name: 首页
  version: 1.0
dubbo:
  application:
    name: portal-web
  registry:
    address: zookeeper://192.168.10.251:2181
    protocol: zookeeper
server:
  port: 8888
druid:
  allow: #?????IP??
    ip: 127.0.0.1
  login: #???????
    user_name: root
    password: root
spring:
  datasource:
    url: jdbc:mysql://192.168.10.251:3306/mall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
#  rabbitmq:
#    host: 192.168.10.33
#    port: 5672
#    virtual-host: /mall
#    username: admin
#    password: admin
#    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  data:
    mongodb:
      host: 192.168.10.251
      port: 27017
      database: micromall
  redis:
    host: 192.168.10.251 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
#  rabbitmq:
#    host: 192.168.10.251
#    port: 5672
#    virtual-host: /mall
#    username: admin
#    password: admin
#    publisher-confirms: true #如果对异步消息需要回调必须设置为true
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mybatis/*.xml
logging:
  level:
    root: info
    com.mall: debug
logstash:
  host: localhost
  enableInnerLog: false

# 自定义redis键值
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 90 # 验证码超期时间
# 自定义消息队列名称
#rabbitmq:
#  queue:
#    name:
#      cancelOrder: cancelOrderQueue
#支付-当面付qrcode存储与访问路径设置
#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mall-portal-secret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24)
#  tokenHead: Bearer #JWT负载中拿到开头
jwt:
  secret: tuling-mall-portal  #服务端私钥（一定不能泄露）
  expiration: 86400   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /user/**
      - /product/**
      - /home/**
      - /order/paySuccess/*
      - /static/qrcode/**
      - /api/webSocket
      - /order/tradeQrCode
#支付-当面付qrcode存储与访问路径设置
#trade:
#  zhifu:
#    qrcode:
#      aliPayPath: /alipay
#      weChatPath: /wechat
#      storePath: C:/temp/qr-code
#      httpBasePath: /static/qrcode
#      paySuccessCallBack: http://yangguo.natapp1.cc/order/paySuccess
trade:
  zhifu:
    qrcode:
      httpBasePath: /static/qrcode
      paySuccessCallBack:  http://j8fhd3.natappfree.cc/order/paySuccess
      storePath: E:/Temp/qr-code
alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: 9021000132619867
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyQVNvsgGz1JWMX+8cQw/+xtA56EbxghWBeArkOM59Y7bokDKR/DTYn6mK46vEhA8IXvt86yaQkBJQ+a4SM0DJgqBe64qKBdEocXfhDG69eEFrbV3Eu7OMWNx7SWXWvMr9Pwvw2jQItDW00ADLpRuLFRmEivZZ2duDVmjwogxsrF53OIeghfW9KI+LCxun7RbKxVFyBzPeOKzQ0jddO7wkjnBh/1bGaajTvzO9YnXEN/PnOepcazYKdxKh3cK93XSsAp75cKI+t5b1H7Im0fKst3PdcnSBFCZ9IzvMlOoM5Pc+y7bduOovOcSD3P8l62SYDqBhdYLhUBGRcEhPhBbaQIDAQAB
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClF11JFy2vjyC6lrohFyt/eohIWJI46WowhuQn6nvZT7ebjz+gavDgCh2/NH4nxM0Zmh9OjG6W077zhUmwPTLH7M9ixXS7yyCYD+M3YVvv7xAGcN5S06l7yX4HLqDT2Yy8k0tcOdgCAbD0dxOv6XzJ++lm05/ozQ4RV24duNcaEDcADMnDjWIkspavBO22L/OLOjQUlVQv5SEBJXfnxG3ub4W7T3BlhW/9nyLN8iaytamVz1uG/4j7lbEJvQHDjGg6aXizHLTGXm+zuRWhf6zUELDfO1n0TPhBNTHEItKlyGaSUb2M9YzGGEhB6sDbcwjhp3XHeQDf12yf/7bSIMTJAgMBAAECggEAGggrH4FWJN6uzH1D8D/VDg7mOnIs7Ghx5CEBDQI+cS/Oxeq6n7L9NHaj5iiC1AaGSMkyspIWRhYxf/i+e9nKjhfbQ7nbBFmtVAz9SRhDBPxvTHSzud/CU9Cb3MoPdhhRxtJ7CZndY8OcgY/dPNnWYYslbJ9mEbFzzGw64tjooiU2PpC7sjnDkJmGbda7e8IMeukwoNdnVQI1yq7iwjEtXTjo/qQZRAzUvh9VGeso2AP3fotUmgkeEtvhY8D6U06ysZtBNUPgF5xYQn94IasbRG4MMLEno1yaItcF3rgdBq+JNocwXB75EptT8MTl5obBlr/1tBM5xFqQqcHXRYh6WQKBgQD7itPQ+o/jNjkLyG+g3lNt0YHh+v763e5GTPbMc4iQ3fhqnbejda4BfmafCq/o6LnGyN5UO7q9pjZNsPBC7YIkLzTK/hz3QkZlnGqscUZaHGw8eOCJNwv3dAQnkYhQ9dwljSGkqRAn8ejX+ZkAxL/h0PTPIYBaIWuu6No/w1w9FwKBgQCoBFWaOqkGxoOsghOoPe+kEqlrRKQq74eBpiTsVN+SY8shEne/QjuXpThV87UeJmpI5okz8y8wmrys7jgO8Y/W8A5o04qhooD6tg5IqJaLQojXuDg5g7nbNebBBpuaV0XI3yCRTVhCdHQ+Sfuse6gZ5gBG7RhdOqwGifLanAb5HwKBgQCCQogiBj8Q+HleIrO76KXnjsDl12bHXroPabe8dG/aJTiJbZc1bLFpUJ2v6obh4/KggFCx6iRwJWylmuUwo3Hrbw61uBYj7Qwrfm63UgmOjH14a1hLdlgaEtg77V9cHZWdVJKBhJM7PEjJ3xVekoSTWfQMd1rSUdBDyY2Ly40ujQKBgFGB8MkmJfN8gEpCvCiFC2lMCFZacU3G77TMleL0dZU9xkAgBmmJRwGVDFReKwIaXrtI40yJb94jYt59nkJZm48I2+Ssovcwr2NwyFMlPgsG1v3Xh6cXKSWX636+puPj7J266MC0hdmPRwkkuOv+/Ri7RG0j/grUOLnfWCoHQTa/AoGAYFRLUgyOKIvGRGKVnKmG+GC8Gc1joWaOLgMCTZGPqe3kwTqAiEgW/3SsrT7OzgL0zpda1nE0N6PbgBhmEm7JCqoFEKdjQyl2NM/XXOjm2zKJ5dTiihWQ169KXviI24atrRTnL/ZjVrb1AXhOn2/4/IdXRUuFcNowz9dYJRetF9E=
  returnUrl: http://localhost:8060/#/pages/money/paySuccess
  notifyUrl: http://zi9aqf.natappfree.cc/notify
mongo:
  insert:
    sqlEnable: true # 用于控制是否通过数据库数据来插入mongo