app:
  name: 首页
  version: 1.0
dubbo:
  application:
    name: portal-web
  registry:
    address: zookeeper://192.168.10.33:2181
    protocol: zookeeper
server:
  port: 8032
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头
spring:
  datasource:
    url: jdbc:mysql://192.168.10.33:3306/mall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: 192.168.10.33
      port: 27017
      database: micromall
  redis:
    host: 192.168.10.33 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 192.168.10.33
    port: 5672
    virtual-host: /mall
    username: admin
    password: admin
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mybatis/*.xml