app:
  name: 首页
  version: 1.0
server:
  port: 8029
dubbo:
  application:
    name: portal-web
  registry:
    address: zookeeper://192.168.10.251:2181
    protocol: zookeeper

jwt:
  secret: tuling-mall-portal  #服务端私钥（一定不能泄露）
  expiration: 86400   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字

secure:
  ignored:
    urls: #安全路径白名单
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /user/**
      - /product/**
      - /home/**
      - /order/paySuccess/*
      - /static/qrcode/**