server:
  port: 8025
# dubbo config
dubbo:
  application:
    name: manager-web
  registry:
    address: zookeeper://192.168.10.33:2181
    protocol: zookeeper
#erver:
#  tomcat:
#    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp