server:
  port: 8025
spring:
  application:
    name: manager-controller
  main:
    allow-circular-references: true
dubbo:
  application:
    name: ${spring.application.name}
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 192.168.10.250:2181
  # dubbo协议在20881端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20888
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000
  # 注册监控中心
  monitor:
    protocol: registry

minio:
  endpoint: http://192.168.10.33:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
jwt:
  secret: tuling-mall-admin  #服务端私钥（一定不能泄露）
  expiration: 86400   #过期时间 60*60*24  =一天
  tokenHead: Bearer #jwt规范  #告诉客户端jwt令牌开头需要加的一个字符串
  tokenHeader: Authorization #告诉客户端你要在请求头里面传什么参数名字
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload